"""Record the numerical behaviour of the network as it exists today.

Run BEFORE any refactor; the resulting JSON is committed and asserted against
by tests/test_golden.py forever after. Any refactor that changes a single bit
of the forward pass, the RNG stream or the mutation operator will fail loudly.

    python tests/golden/_generate.py
"""
import json
import os
import random
import sys

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", ".."))
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..", "src"))

try:
    from nncar import neural_network as nn  # after the restructure
except ImportError:
    import neural_network as nn             # before it

OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "network_golden.json")


def snapshot():
    # A fixed RNG stream makes the whole snapshot reproducible. Box-Muller
    # consumes exactly two random() draws per call, so pinning the seed pins
    # every weight in the network.
    random.seed(20240828)

    net = nn.Network()
    weights = [[layer.weights, layer.bias] for layer in net.layers]

    class FakeCar:
        pass

    cases = []
    for raw in (
        [[500.0], [600.0], [700.0], [600.0], [500.0], [5.0]],
        [[0.0], [0.0], [0.0], [0.0], [0.0], [0.0]],
        [[1.0], [-1.0], [0.5], [-0.5], [0.25], [-12.0]],
        [[12.5], [7.5], [3.25], [900.0], [1e-3], [11.9]],
    ):
        car = FakeCar()
        car.network = net
        car.inputs = [row[:] for row in raw]
        cases.append({"inputs": raw, "output": list(nn.forward_propagation(car))})

    # Mutation is stateful, so record it as an ordered sequence off the same seed.
    random.seed(99)
    mutated = nn.Network()
    trace = []
    for _ in range(3):
        mutated.mutate()
        trace.append(mutated.layers[0].weights[0][:3] + mutated.layers[-1].bias[0][:1])

    random.seed(7)
    normals = [nn.random_normal() for _ in range(10)]

    return {
        "_comment": "Generated by tests/golden/_generate.py against the pre-refactor code. Do not hand-edit.",
        "architecture": [[len(l.weights[0]), len(l.weights)] for l in net.layers],
        "parameter_count": sum(len(l.weights) * len(l.weights[0]) + len(l.bias) for l in net.layers),
        "seeded_weights": weights,
        "forward_cases": cases,
        "mutation_trace": trace,
        "random_normal_stream": normals,
        "tanh_probe": [nn.Layer.tanh(None, x) for x in (-3.0, -0.5, 0.0, 0.5, 3.0, 19.9)],
    }


if __name__ == "__main__":
    data = snapshot()
    with open(OUT, "w", encoding="utf-8") as fh:
        json.dump(data, fh, indent=1)
    print("wrote", OUT)
    print("architecture:", data["architecture"])
    print("parameters:", data["parameter_count"])
    print("forward case 0:", data["forward_cases"][0]["output"])
